# Generated by Django 3.1.5 on 2021-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=5)),
                ('letters_drawn', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
