version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=scrabble
      - POSTGRES_USER=scrabble
      - POSTGRES_PASSWORD=scrabble
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/picker
    ports:
      - "8000:8000"
    depends_on:
      - db
