version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=scrabble
      - POSTGRES_USER=scrabble
      - POSTGRES_PASSWORD=scrabble
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrabble"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    entrypoint: |
      watchmedo auto-restart \
        --recursive \
        --pattern="*.py" \
        --directory="." \
        python manage.py runserver 0.0.0.0:8000                     
    volumes:
      - .:/scrabble_picker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
