# Generated by Django 3.1.5 on 2021-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('letters_remaining', models.CharField(default='aaaaaaaaabbccddddeeeeeeeeeeeeffggghhiiiiiiiiijkllllmmnnnnnnooooooooppqrrrrrrssssttttttuuuuvvwwxyyz**', max_length=100)),
            ],
        ),
    ]
