# Generated by Django 3.1.5 on 2021-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='letters_remaining',
        ),
        migrations.AddField(
            model_name='game',
            name='letters_drawn',
            field=models.TextField(default=''),
        ),
    ]
