# Generated by Django 3.1.5 on 2021-01-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0002_auto_20210124_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='letters_drawn',
            field=models.CharField(default='', max_length=27),
        ),
    ]
